### PR TITLE
[WIP - Help needed] Add a readme

### LINKED ISSUE #1: Create a README
A README would make it a lot easier for people to be able to contribute!  Things that I can think of that should be included:

- How to set up a dev environment
- How to build
- How to test
- Format of POI XML paths (could be in the POIs directory)

Thanks 😄

### PR DESCRIPTION
**Pull request by elias-knodel**
## Description
This adds a readme with all needed information to set this project up for development,
(Small extra change: extends the .gitignore because when you build it some folders get generated)

## Related issue
Fixes  #1

## How can this be tested?
Set it up like its written in the README.md and look if it works without any complications.

### CODE REVIEW

**Comment by elias-knodel** [comment]
I don't know the exact workflow with TacO and VS. It worked for me like this but maybe a little more details for like how we can get a working dev environment would be useful.

**Comment by elias-knodel** [comment]
I also would suggest changing the license... (look at #2)

**Comment by logan001** [comment]
are you sure thats the way to build it?
because i get a lot of dlls in the release folder. compare to the program release by the author this build seems to generate too much crap. also have you test it on a clean windows machine? will it work or will need some other dependencies that comes with VS

**Comment by agarie** [comment]
Is there any write-up showing how to build TacO? I'm not well-versed in `msbuild` so might be doing something wrong. There are a bunch of issues I think I could work on but wanna make sure I can get the project built correctly before tackling them. :)

**Comment by BoyC** [comment]
It's literally "load .sln into visual studio and press build"...

**Pull request closed without merging**
